DELETE FROM product_images;
DELETE FROM products;

WITH seed(slug,title,description,category_slug,selection,materials,measurements,price_ars,price_note) AS (
  VALUES
  ('sujeta-lentes-cristalis','Sujeta LENTES CRISTALIS','Realizado con cristalitos de diferentes formas, colores y tamaños, con cadena de acero quirúrgico. Personalizamos.','accesorio','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',15000,'Precio: $ 15.000'),
  ('colar-arandelas','Colar ARANDELAS','Confeccionado con tientos de gamuza y   centro de finas arandelas en acero quirúgico. Recordá que personalizamos. Puede realizarse en colores de tu preferencia y el largo que te guste.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',25000,'Precio promedio :  $ 25.000 (sujeto a materiales elegidos)'),
  ('choker-boton-strass','Choker BOTON STRASS','Confeccionado con tientos de gamuza, pasantes de acero quirúrgico y  hermoso dije , muy fino, con detalle de piedra de strass. Recordá que personalizamos. Puede realizarse en colores de tu preferencia.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio promedio :  $ 20.000 (sujeto a materiales elegidos)'),
  ('choker-boton-swarovski','Choker BOTON Swarovski','Confeccionado con tientos de gamuza, pasantes de acero quirúrgico y  hermoso dije , muy fino, con detalle de piedritas Swarovski . Recordá que personalizamos. Puede realizarse en colores de tu preferencia.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio :  $ 20.000'),
  ('pulseras-cristalis-cubo','Pulseras CRISTALIS CUBO','Realizadas con cristales cubo combinados con separadores, terminales y mosquetón de acero quirúrgico.  También pueden realizarse elastizadas. El color es a tu elección. Consultanos disponibilidad.','pulsera','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',13000,'Precio promedio $ 13.000 (sujeto a cristales y  adicionales elegidos).'),
  ('collar-fiumina-mix','Collar FIUMINA MIX','Realizado con donas de Fimo, combinadas con mostacillones y  pasantes metálicos.  Cierre marinero acero quirúrgico y  dije letra de tu inicial.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio: $ 20.000'),
  ('collar-eslabones-inicial','Collar ESLABONES INICIAL','Collar de eslabones niquelados con dije de letras inicales en acero quirúrgico.  Tenemos distintos tamaños.  Consultanos disponibilidad.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio letras chicas: $ 20.000 / Precio Maxi letra: $ 25. 000'),
  ('tientos-con-dijes-desmontables','Tientos con dijes Desmontables','Tientos de gamuza con terminaciones muy finas de cristalitos.  Los dijes son a elección y se pueden intercambiar o sacarse si preferis usar el tiento solo. Hay variedad de colores y dijes.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',16000,'Precio promedio :  $ 16.000 (sujeto a dijes elegidos)'),
  ('tientos-con-dijes-desmontables-2','Tientos con dijes Desmontables','Tientos de gamuza con terminaciones  metálicas. Los dijes son a elección y se pueden intercambiar o sacarse si preferis usar el tiento solo. Hay variedad de colores y dijes.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',13000,'Precio promedio :  $ 13.000 (sujeto a dijes elegidos)'),
  ('collar-cuore-movible','Collar Cuore movible','Collar realizado con gamuza y dije esmaltado.  Detalle terminal con cristales.   Se puede regular su altura para usarlo con distintos escotes.   Muy delicado! Hay variedad de colores de gamuzas y dijes.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio promedio :  $ 20.000 (sujeto a dijes elegidos)'),
  ('collar-aria','Collar ARIA','Cadena muy fina de Acero Quirúrgico combinada con pasantes del mismo material y arandelas de fimo.  Hay variedad de colores y  dijes para elegir. Se realizan a pedido y en el largo que solicites.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio promedio :  $ 20.000 (sujeto a materiales elegidos)'),
  ('tiento-coquette','Tiento Coquette','Corbatín de gamuza de altura regulable con dije de moño niquelado.  Hay variedad de colores para que puedas complementar y engamar otros colgantes.','dije','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',15000,'Precio promedio :  $ 15.000 (sujeto a materiales elegidos)'),
  ('choker-mix-piedras-naturales','Choker Mix Piedras Naturales','Confeccionados con piedras naturales alternadas con bolitas de acero quirúrgico. Súper nobles y duraderos. Recordá que personalizamos. Pueden realizarse en colores de tu preferencia.','colgante','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',18000,'Precio promedio :  $ 28.000 (sujeto a materiales elegidos)'),
  ('corbatero-dije-penta','Corbatero Dije Penta','Realizado con gamuzas de distintos colores.  Pasantes metálicos y de piedra reconstituida.   Terminaciones muy finas de cristales varios.','accesorio','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',18000,'Precio  :  $ 18.000'),
  ('corbat-n-ovalo','Corbatín Ovalo','Corbatín de gamuza de altura regulable con dije ovalado y niquelado.  Detalle terminal con cristales.   Se puede regular su altura para usarlo con distintos escotes.   Muy delicado!','accesorio','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',18000,'Precio :  $  18.000'),
  ('corbat-n-triple-pasante-cristal','Corbatín triple pasante Cristal','Corbatín de triple gamuza de altura regulable, jugando con su finísimo pasante con cristales. Se puede regular su altura para usarlo con distintos escotes.   Muy delicado! Hay variedad de colores. Consultanos disponibilidad.','accesorio','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',22000,'Precio :  $ 22.000'),
  ('pulseras-acero-q-y-cristalis','Pulseras Acero Q. y Cristalis','Realizadas con bolitas de acero quirúrgico con detalles de cristales de colores, elastizadas o con mosquetón de también de acero quirúrgico. Ideales para usarlas todo el tiempo! Los colores son a  tu elección. Consultanos disponibilidad. o $ 23.500 (de 4") (sujeto a cristales y  adicionales elegidos).','pulsera','s','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio promedio $ 20.000  (de 3")'),
  ('collar-fimo-cubo','Collar Fimo Cubo','Collares confeccionados con mix de materiales muy fieles. Se pueden combinar fimo de distintos colores con fimos cúbicos, cristales, pasantes de metal o de acero quirúrgico.  Te mostramos opciones y elegis a tu gusto. Se realizan a pedido y en el largo que solicites.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio promedio :  $ 20.000 (sujeto a materiales elegidos)'),
  ('straps-carteras','Straps Carteras','Ideales para embellecer  y darle un toque a tus carteras, llaveros, pendrives, entre otras opciones. Hay muchos diseños, colores y dijes. No dudes en consultarnos y recordá que personalizamos.','colgante','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',17000,'Precio: $ 17.000'),
  ('collar-tesi','Collar TESI','Contiene piedras ágatas, cristalitos y mostacillones.  Se puede confeccionar en tonos que sean de tu agrado. Podes sumarle la pulsera PIETRA haciendo juego. Consultanos disponibilidad. Se realizan a pedido y en  el largo que solicites.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',25000,'Precio: $  25.000'),
  ('collar-olimpic','Collar OLIMPIC','Chokers confeccionados con anillas labradas o lisas y mosquetón acero quirúrgico. Combinados con diferentes colores de cordones o gamuzas.  Lo elegís a tu gusto. Se realizan a pedido y en el largo que solicites.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',22000,'Precio:  $ 22.000'),
  ('collar-picoli','Collar PICOLI','Collar estilo "corbatero".  Realizado con piedras naturales, cristales y dijes de acero. Se puede confeccionar en tonos que sean de tu agrado. Consultanos disponibilidad. Se realizan a pedido y en el largo que prefieras.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',35000,'Precio: $  35.000'),
  ('pulsera-pietra','Pulsera PIETRA','Confeccionadas con piedras naturales,  combinadas con separadores, terminales y mosquetón en acero quirúrgico. El color es a tu elección. Consultanos disponibilidad.','pulsera','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',15000,'Precio promedio $ 15.000 (sujeto a adicionales elegidos).'),
  ('collar-maxi-cuore','Collar MAXI CUORE','Cadena con maxi dije calado en forma de corazón, todo en acero quirúrgico.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',22000,'Precio: $ 22.000'),
  ('dijes-movibles','Dijes MOVIBLES','Variedad de  dijes movibles, realizados con piedras naturales de múltiples colores, sujetas a arandelas y/o mosquetones de acero quirúrgico.','dije','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',7000,'Precio: $ 7.000'),
  ('pulseras-cristalis','Pulseras CRISTALIS','Son elastizadas.  Están realizadas con cristalitos de distintos colores, y formas combinados con separadores y terminales de acero quirúrgico. El color es a tu elección.  Consultanos disponibilidad.','pulsera','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',9000,'Precio promedio sólo cristalitos $ 9.000'),
  ('choker-centro-cubo','Choker CENTRO CUBO','Modelo Choker.    Para llevar ceñido al cuello, o en el largo que prefieras. Confeccionado con mostacillones de la india, combinados con bolitas niqueladas y cierre mosquetón de acero quirúrgico. Se realizan a pedido y en varios colores y medidas. Consultá disponibilidad.','accesorio','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',15000,'Precio:  $ 15.000'),
  ('pulseras-tubo','Pulseras TUBO','Son elastizadas. Confeccionadas con maxi cristales de distintos colores, combinados con separadores, terminales y tubo alargado todo de acero quirúrgico. El color es a tu elección.  Consultanos disponibilidad.','pulsera','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',15000,'Precio:  $ 15.000 (sujeto a adicionales elegidos)'),
  ('collar-r-tola-tambure','Collar RαTOLA TAMBURE','Confeccionado con argollas onduladas, irregulares y labradas de metal, complementadas con pasantes y separadores de acero quirúrgico. Podes elegir el color de gamuza. Consultanos disponibilidad. Se realizan a pedido y en la medida que solicites','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',15000,'Precio: $ 15000'),
  ('collar-eslab-n-mix','Collar ESLABαN MIX','Eslabones niquelados súper livianos, combinados con centro de cristales y discos de fimo de diversos colores.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio: $ 20.000'),
  ('collar-glam','Collar GLAM','Hermoso collar realizado con perlas de vidrio  opacas, unidas por arandelas en acero quirúrgico.  Su terminal es metálico, de diseño muy fino y su mosquetón, de acero quirúrgico . Podes combinarlo con la pulsera GLAM.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',25000,'Precio:  $ 35.000'),
  ('straps-celular','Straps CELULAR','Ideales para embellecer y  sujetar de manera segura el celular.   Realizado a elección,  con cristalitos,  pasantes acero quirúrgico, y detalles (ojo turco y otros). Opción detalle con letra inicial nombre. Hay muchos diseños, colores y dijes. No dudes en consultarnos.','colgante','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',18000,'Precio: $ 18.000'),
  ('collar-myreli','Collar MYRELI','Collar estilo "corbatero" en cordón, argollas y pasantes metálicos. Hay opción en otros colores. Consultanos.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',15000,'Precio: $ 15.000'),
  ('collar-fiumina-mix-2','Collar FIUMINA MIX','Realizado con donas de Fimo, combinadas con mostacillones y  pasantes metálicos. Cierre en acero quirúrgico.  Lleva dije en acero blanco.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio: $ 20.000'),
  ('pulseras-cristalis-maxi','Pulseras CRISTALIS MAXI','Son elastizadas.  Están realizadas con cristales grandes combinados con separadores y terminales de acero quirúrgico. Hay opciones de colores.  Consultanos disponibilidad.','pulsera','s','Piedra sintética y acero','Largo regulable: 40 a 46 cm',13000,'Precio promedio $ 13.000'),
  ('collar-eslab-n-r-tola','Collar ESLABαN RαTOLA','Cadena de eslabones pequeños, color plata o dorado.  Súper liviana. Diseño corbatero.  Puede combinarse con lateral de perlas de vidrio o cristales. Podes personalizarlo a tu gusto.  Consultanos opciones y disponibilidad.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio: $ 20.000 (todo eslabones)'),
  ('collar-regia','Collar REGIA','Realizado con cristales combinados con pasantes y dijes metálicos. Cierre mosquetón acero quirúrgico.  Súper elegante. El color y el dije, pueden ser a tu gusto.  Consultanos opciones y disponibilidad.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',23000,'Precio: $ 23.000'),
  ('collar-bola-acero','Collar BOLA ACERO','Collar con cadena y bola pasante, todo en acero quirúrgico.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',15000,'Precio: $ 15.000'),
  ('collar-doble-bola-acero','Collar DOBLE BOLA ACERO','Collar con doble cadena, en cascada, y dijes bola pasantes, todo en acero quirúrgico.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',24000,'Precio:  $ 24.000'),
  ('collar-dijes-frases','Collar DIJES FRASES','Collar con  dije con frases, todo en acero quirúrgico.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',15000,'Precio: $ 15.000'),
  ('pulsera-eslabones-mini','Pulsera ESLABONES MINI','Pulsera de eslabones pequeños, en acero quirúrgico, con dije letra y cristalito. Podes elegir dijes.  Hay otras variantes. Consultanos opciones y disponibilidad.','pulsera','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',13000,'Precio: $ 13.000'),
  ('collar-barrita','Collar BARRITA','Collar con cadena y dije barrita macizo, todo en acero quirúrgico. Ideal para agregarle algún dije movible de piedra natural.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio: $ 20.000'),
  ('collar-eslab-n-multi-dijes','Collar ESLABαN MULTI DIJES','Cadena de eslabones de aluminio color plata. Súper livianas. Ideales para llevar solas o complementando otros collares. Podes elegir dijes.  Hay otras variantes. Consultanos opciones y disponibilidad.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',18000,'Precio: $ 18.000'),
  ('collar-anabela','Collar ANABELA','Mezcla de piedras naturales con bolitas y pasantes de metal. Se pueden confeccionar en colores a tu gusto.  Está pensado para usarlo por mitades, combinando dos gamas de colores distintas para usarlo con diferentes outfits.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',23000,'Precio:  $ 23.000'),
  ('collar-anellis','Collar ANELLIS','Modelo Choker.    Para llevar ceñido al cuello, o en el largo que prefieras. Se puede confeccionar con anillas labradas o lisas. También en diferentes colores de cordones o gamuzas. Lo elegís a tu gusto. Se realizan a pedido y en la medida que solicites.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',19000,'Precio:  $ 19.000'),
  ('collar-r-tola-doble','Collar RαTOLA DOBLE','Confeccionado en cordón, con argollas onduladas, irregulares y labradas de metal, complementadas con bolitas de acero quirúrgico. Podes elegir el color de cordón. Se realizan a pedido y en el largo que solicites.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',17000,'Precio:  $ 17.000'),
  ('collar-fiumina-mix-3','Collar FIUMINA MIX','Realizado con donas de Fimo y mostacillones.  Combinado con separadores metálicos.  Cierre marinero acero quirúrgico y dijes de metal. Podes sumarle la letra de tu inicial (costo adicional)','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio: $ 20.000'),
  ('collar-cuore','Collar CUORE','Confeccionado en gamuza y con bolitas de acero quirúrgico.  Dije corazón de metal, a tu gusto. Elegí color y lo adaptamos a tu medida.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',18000,'Precio: $ 18.000'),
  ('collar-semili','Collar SEMILI','Combinación de mostacillones checos, comunes y dijes de metal. Se puede cambiar color, a tu gusto y se adapta a tu medida.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',18000,'Precio: $ 18.000'),
  ('pulsera-pietra-2','Pulsera PIETRA','Confeccionadas con piedras naturales y cristales,   a tu medida. Pueden confeccionarse cerradas -elastizadas- o abiertas, con mosquetones clásicos o cierres marineros, con o sin dijes.   También puede llevar la letra de tu inicial. El color es a tu elección. Consultanos disponibilidad.','pulsera','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Línea especial con separadores, terminales y mosquetón, en acero quirúrgico: Precio promedio $ 20.000 (sujeto a adicionales elegidos).'),
  ('pulsera-entrelazada','Pulsera ENTRELAZADA','Confeccionada con gamuzas de colores engamados y pasantes metálicos. Podes elegir colores y se realiza a tu medida.','pulsera','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',25000,'Precio:  $ 25.000'),
  ('pulseras-pietra','Pulseras PIETRA','Confeccionadas con piedras naturales y cristales,   a tu medida. Pueden confeccionarse cerradas -elastizadas- o abiertas, con mosquetones clásicos o cierres marineros, con o sin dijes.   También puede llevar la letra de tu inicial. El color es a tu elección. Consultanos disponibilidad.','pulsera','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Línea especial con separadores, terminales y mosquetón, en acero quirúrgico: Precio promedio $ 20.000 (sujeto a adicionales elegidos).'),
  ('collar-fiumina','Collar FIUMINA','Realizado con donas de Fimo. Combinado con separadores metálicos.  Cierre marinero acero quirúrgico y dijes de metal. Podes sumarle la letra de tu inicial (costo adicional)','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio: $ 20.000'),
  ('collar-perlines','Collar PERLINES','Collares confeccionados en mostacillones y mostacillas con cierre de acero quirúrgico.   Hay variedad de colores y medidas. Consultanos.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',15000,'Precio promedio: $ 15.000 (sujeto al largo elegido)'),
  ('collar-r-tola-rosso','Collar RαTOLA ROSSO','Confeccionado con argollas onduladas e irregulares de metal, complementadas con pasantes y separadores de acero quirúrgico. Podes elegir otro color de cordón y piedra. Consultanos disponibilidad. Se realizan a pedido y en la medida que prefieras.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio:  $ 18.000'),
  ('collar-fiumina-2','Collar FIUMINA','Realizado con donas de Fimo. Combinado con pasantes metálicos.  Cierre marinero acero quirúrgico y dijes de metal. Podes sumarle la letra de tu inicial (costo adicional)','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio: $ 20.000'),
  ('corbatero-foglia','Corbatero FOGLIA','Realizado con gamuzas o cordones.  Hay variedad de colores. Sus pasantes y dijes son de metal y acero quirúrgico.     Podes diseñarlos como más te guste.','accesorio','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',20000,'Precio:  $ 20.000'),
  ('fiumina-oto-al','FIUMINA OTOÑAL','Confeccionado con donas de fimo.     Combinado con separadores y pasantes metálicos y bolitas de acero quirúrgico. Lleva un dije metálico importante. Podes elegir otros dijes similares o de menor tamaño.','accesorio','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',22000,'Precio:  $ 22.000'),
  ('collar-tesi-mix','Collar TESI MIX','Realizado con piedras ágatas, y cristalitos. Combinado con cadenas metálicas.  Se puede confeccionar en tonos que sean de tu agrado y como siempre, podes personalizarlo. No dudes en consultarnos.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',28000,'Precio: $ 28.000'),
  ('collar-silvani','Collar SILVANI','Confeccionado con cristales de dos tamaños,  en composé.   Lleva dije letra  o de  otro diseño,  en acero quirúrgico, a elección. El color es a tu gusto. Consultanos disponibilidad.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',23000,'Precio: $ 23.000'),
  ('pulsera-glam','Pulsera GLAM','Bella pulsera realizada con perlas opacas, unidas por arandelas en acero quirúrgico.  Su terminal es metálico de diseño muy fino y su mosquetón, de acero. Podes combinarla con el collar GLAM.','pulsera','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',22000,'Precio:  $ 22.000'),
  ('collar-eslab-n-dor','Collar ESLABαN DORÉ','Cadena de eslabones de aluminio dorado. Súper livianas. Ideales para llevar solas o complementando otros collares. Podes elegir dijes.  Hay otras variantes. Consultanos opciones y disponibilidad.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',17000,'Precio promedio: $ 17.000'),
  ('collar-eslab-n-plata','Collar ESLABαN PLATA','Cadena de eslabones de aluminio color plata. Súper livianas. Ideales para llevar solas o complementando otros collares. Podes elegir dijes.  Hay otras variantes. Consultanos opciones y disponibilidad.','collar','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',17000,'Precio promedio: $ 17.000'),
  ('pulsera-eslabones','Pulsera ESLABONES','Pulsera realizada con eslabones de aluminio color plata con dijes y cierre marinero. Podes elegir dijes.  Hay otras variantes. Consultanos opciones y disponibilidad.','pulsera','n','Piedra sintética y acero','Largo regulable: 40 a 46 cm',12000,'Precio: $ 12.000')
)
INSERT INTO products (slug,title,description,category_id,selection,materials,measurements,price_ars,price_note)
SELECT seed.slug,seed.title,seed.description,categories.id,seed.selection,seed.materials,seed.measurements,seed.price_ars,seed.price_note
FROM seed JOIN categories ON categories.slug=seed.category_slug;

WITH seed(product_slug,object_key,alt_text,sort_order,is_primary) AS (
  VALUES
  ('sujeta-lentes-cristalis','001_sujeta_lentes_cristalis.jpg','Sujeta LENTES CRISTALIS',0,1),
  ('colar-arandelas','002_colar_arandelas.jpg','Colar ARANDELAS',0,1),
  ('choker-boton-strass','003_choker_boton_strass.jpg','Choker BOTON STRASS',0,1),
  ('choker-boton-swarovski','004_choker_boton_swarovski.jpg','Choker BOTON Swarovski',0,1),
  ('pulseras-cristalis-cubo','005_pulseras_cristalis_cubo.jpg','Pulseras CRISTALIS CUBO',0,1),
  ('collar-fiumina-mix','006_collar_fiumina_mix.jpg','Collar FIUMINA MIX',0,1),
  ('collar-eslabones-inicial','007_collar_eslabones_inicial.jpg','Collar ESLABONES INICIAL',0,1),
  ('tientos-con-dijes-desmontables','008_tientos_con_dijes_desmontables.jpg','Tientos con dijes Desmontables',0,1),
  ('tientos-con-dijes-desmontables-2','009_tientos_con_dijes_desmontables_2.jpg','Tientos con dijes Desmontables',0,1),
  ('collar-cuore-movible','010_collar_cuore_movible.jpg','Collar Cuore movible',0,1),
  ('collar-aria','011_collar_aria.jpg','Collar ARIA',0,1),
  ('tiento-coquette','012_tiento_coquette.jpg','Tiento Coquette',0,1),
  ('choker-mix-piedras-naturales','013_choker_mix_piedras_naturales.jpg','Choker Mix Piedras Naturales',0,1),
  ('corbatero-dije-penta','014_corbatero_dije_penta.jpg','Corbatero Dije Penta',0,1),
  ('corbat-n-ovalo','015_corbatin_ovalo.jpg','Corbatín Ovalo',0,1),
  ('corbat-n-triple-pasante-cristal','016_corbatin_triple_pasante_cristal.jpg','Corbatín triple pasante Cristal',0,1),
  ('pulseras-acero-q-y-cristalis','017_pulseras_acero_q_y_cristalis.jpg','Pulseras Acero Q. y Cristalis',0,1),
  ('collar-fimo-cubo','018_collar_fimo_cubo.jpg','Collar Fimo Cubo',0,1),
  ('straps-carteras','019_straps_carteras.jpg','Straps Carteras',0,1),
  ('collar-tesi','020_collar_tesi.jpg','Collar TESI',0,1),
  ('collar-olimpic','021_collar_olimpic.jpg','Collar OLIMPIC',0,1),
  ('collar-picoli','022_collar_picoli.jpg','Collar PICOLI',0,1),
  ('pulsera-pietra','023_pulsera_pietra.jpg','Pulsera PIETRA',0,1),
  ('collar-maxi-cuore','024_collar_maxi_cuore.jpg','Collar MAXI CUORE',0,1),
  ('dijes-movibles','025_dijes_movibles.jpg','Dijes MOVIBLES',0,1),
  ('pulseras-cristalis','026_pulseras_cristalis.jpg','Pulseras CRISTALIS',0,1),
  ('choker-centro-cubo','027_choker_centro_cubo.jpg','Choker CENTRO CUBO',0,1),
  ('pulseras-tubo','028_pulseras_tubo.jpg','Pulseras TUBO',0,1),
  ('collar-r-tola-tambure','029_collar_rotola_tambure.jpg','Collar RαTOLA TAMBURE',0,1),
  ('collar-eslab-n-mix','030_collar_eslabon_mix.jpg','Collar ESLABαN MIX',0,1),
  ('collar-glam','031_collar_glam.jpg','Collar GLAM',0,1),
  ('straps-celular','032_straps_celular.jpg','Straps CELULAR',0,1),
  ('collar-myreli','033_collar_myreli.jpg','Collar MYRELI',0,1),
  ('collar-fiumina-mix-2','034_collar_fiumina_mix_2.jpg','Collar FIUMINA MIX',0,1),
  ('pulseras-cristalis-maxi','035_pulseras_cristalis_maxi.jpg','Pulseras CRISTALIS MAXI',0,1),
  ('collar-eslab-n-r-tola','036_collar_eslabon_rotola.jpg','Collar ESLABαN RαTOLA',0,1),
  ('collar-regia','037_collar_regia.jpg','Collar REGIA',0,1),
  ('collar-bola-acero','038_collar_bola_acero.jpg','Collar BOLA ACERO',0,1),
  ('collar-doble-bola-acero','039_collar_doble_bola_acero.jpg','Collar DOBLE BOLA ACERO',0,1),
  ('collar-dijes-frases','040_collar_dijes_frases.jpg','Collar DIJES FRASES',0,1),
  ('pulsera-eslabones-mini','041_pulsera_eslabones_mini.jpg','Pulsera ESLABONES MINI',0,1),
  ('collar-barrita','042_collar_barrita.jpg','Collar BARRITA',0,1),
  ('collar-eslab-n-multi-dijes','043_collar_eslabon_multi_dijes.jpg','Collar ESLABαN MULTI DIJES',0,1),
  ('collar-anabela','044_collar_anabela.jpg','Collar ANABELA',0,1),
  ('collar-anellis','045_collar_anellis.jpg','Collar ANELLIS',0,1),
  ('collar-r-tola-doble','046_collar_rotola_doble.jpg','Collar RαTOLA DOBLE',0,1),
  ('collar-fiumina-mix-3','047_collar_fiumina_mix_3.jpg','Collar FIUMINA MIX',0,1),
  ('collar-cuore','048_collar_cuore.jpg','Collar CUORE',0,1),
  ('collar-semili','049_collar_semili.jpg','Collar SEMILI',0,1),
  ('pulsera-pietra-2','050_pulsera_pietra_2.jpg','Pulsera PIETRA',0,1),
  ('pulsera-entrelazada','051_pulsera_entrelazada.jpg','Pulsera ENTRELAZADA',0,1),
  ('pulseras-pietra','052_pulseras_pietra.jpg','Pulseras PIETRA',0,1),
  ('collar-fiumina','053_collar_fiumina.jpg','Collar FIUMINA',0,1),
  ('collar-perlines','054_collar_perlines.jpg','Collar PERLINES',0,1),
  ('collar-r-tola-rosso','055_collar_rotola_rosso.jpg','Collar RαTOLA ROSSO',0,1),
  ('collar-fiumina-2','056_collar_fiumina_2.jpg','Collar FIUMINA',0,1),
  ('corbatero-foglia','057_corbatero_foglia.jpg','Corbatero FOGLIA',0,1),
  ('fiumina-oto-al','058_fiumina_otonal.jpg','FIUMINA OTOÑAL',0,1),
  ('collar-tesi-mix','059_collar_tesi_mix.jpg','Collar TESI MIX',0,1),
  ('collar-silvani','060_collar_silvani.jpg','Collar SILVANI',0,1),
  ('pulsera-glam','061_pulsera_glam.jpg','Pulsera GLAM',0,1),
  ('collar-eslab-n-dor','062_collar_eslabon_dore.jpg','Collar ESLABαN DORÉ',0,1),
  ('collar-eslab-n-plata','063_collar_eslabon_plata.jpg','Collar ESLABαN PLATA',0,1),
  ('pulsera-eslabones','064_pulsera_eslabones.jpg','Pulsera ESLABONES',0,1)
)
INSERT INTO product_images (product_id,object_key,alt_text,sort_order,is_primary)
SELECT products.id,seed.object_key,seed.alt_text,seed.sort_order,seed.is_primary
FROM seed JOIN products ON products.slug=seed.product_slug;
