import { useEffect, useState } from 'react'

type AdminProduct = { id: number; title: string; description: string; materials: string; measurements: string; price_ars: number; price_note: string; selection: string; category_slug: string; category_name: string; images: string[] }
type Category = { slug: string; name: string }
type FormState = { id?: number; title: string; selection: boolean; category: string; description: string; materials: string; measurements: string; price_note: string; price_ars: string; image_1: string; image_2: string }

const emptyForm: FormState = { title: '', selection: false, category: 'accesorio', description: '', materials: '', measurements: '', price_note: '', price_ars: '', image_1: '', image_2: '' }

export default function Admin() {
  const [password, setPassword] = useState('')
  const [loggedIn, setLoggedIn] = useState(false)
  const [products, setProducts] = useState<AdminProduct[]>([])
  const [categories, setCategories] = useState<Category[]>([])
  const [form, setForm] = useState<FormState>(emptyForm)
  const [editing, setEditing] = useState(false)
  const [error, setError] = useState('')
  const load = () => Promise.all([fetch('/api/admin/products'), fetch('/api/admin/categories')]).then(async ([a, b]) => { if (!a.ok || !b.ok) throw new Error(); setProducts(await a.json()); setCategories(await b.json()) }).catch(() => setLoggedIn(false))
  useEffect(() => { load() }, [])
  async function login(event: React.FormEvent) { event.preventDefault(); setError(''); const response = await fetch('/api/admin/login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ password }) }); if (!response.ok) { setError('Contraseña incorrecta'); return }; setLoggedIn(true); setPassword(''); load() }
  function edit(product: AdminProduct) { setForm({ id: product.id, title: product.title, selection: product.selection === 's', category: product.category_slug, description: product.description, materials: product.materials, measurements: product.measurements, price_note: product.price_note, price_ars: String(product.price_ars), image_1: product.images[0] || '', image_2: product.images[1] || '' }); setEditing(true); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  async function save(event: React.FormEvent) { event.preventDefault(); setError(''); const response = await fetch('/api/admin/products', { method: form.id ? 'PUT' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) { setError('No se pudo guardar el producto'); return }; setForm(emptyForm); setEditing(false); await load() }
  if (!loggedIn) return <main className="catalog-page admin-page"><section className="catalog-heading"><p className="eyebrow">Due Sorelas / Administración</p><h1>Backoffice</h1><p>Ingresá para administrar el catálogo.</p></section><form className="admin-login" onSubmit={login}><label>Contraseña<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" required /></label>{error && <p role="alert">{error}</p>}<button className="button" type="submit">Ingresar</button></form></main>
  return <main className="catalog-page admin-page"><section className="catalog-heading"><p className="eyebrow">Due Sorelas / Administración</p><h1>Productos</h1><p>{products.length} productos cargados en D1.</p></section><div className="admin-toolbar"><button className="button" onClick={() => { setForm(emptyForm); setEditing(true) }}>Nuevo producto</button><button className="button" onClick={() => fetch('/api/admin/logout', { method: 'POST' }).then(() => setLoggedIn(false))}>Cerrar sesión</button></div>{editing && <form className="admin-form" onSubmit={save}><div className="admin-form-grid"><label>Título<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Categoría<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{categories.map((category) => <option value={category.slug} key={category.slug}>{category.name}</option>)}</select></label><label>Precio ARS<input type="number" min="0" value={form.price_ars} onChange={(e) => setForm({ ...form, price_ars: e.target.value })} /></label><label className="admin-check"><input type="checkbox" checked={form.selection} onChange={(e) => setForm({ ...form, selection: e.target.checked })} /> Producto destacado</label><label>Descripción<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label>Materiales<input value={form.materials} onChange={(e) => setForm({ ...form, materials: e.target.value })} /></label><label>Medidas<input value={form.measurements} onChange={(e) => setForm({ ...form, measurements: e.target.value })} /></label><label>Comentario de precio<input value={form.price_note} onChange={(e) => setForm({ ...form, price_note: e.target.value })} /></label><label>Imagen 1 (URL Cloudinary)<input value={form.image_1} onChange={(e) => setForm({ ...form, image_1: e.target.value })} /></label><label>Imagen 2 (URL Cloudinary)<input value={form.image_2} onChange={(e) => setForm({ ...form, image_2: e.target.value })} /></label></div>{error && <p role="alert">{error}</p>}<button className="button" type="submit">Guardar producto</button><button type="button" className="text-link" onClick={() => setEditing(false)}>Cancelar</button></form>}<div className="admin-table"><div className="admin-row admin-head"><span>Producto</span><span>Categoría</span><span>Precio</span><span>Acciones</span></div>{products.map((product) => <div className="admin-row" key={product.id}><span>{product.title}</span><span>{product.category_name}</span><span>${product.price_ars.toLocaleString('es-AR')}</span><button className="text-link" onClick={() => edit(product)}>Editar</button></div>)}</div></main>
}
